sonar.projectKey=kindred-98_Costes_Token
sonar.organization=kindred-98
sonar.projectName=Costes_Token
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

